/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID || "ztxlcatckspsdtkepmwy";
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "";

// Supabase configuration
export const supabaseConfig = {
  url: `https://${projectId}.supabase.co`,
  anonKey: publicAnonKey,
};
